print("Hola mi onmbre es leonardo")
print("Tengo 17 años")
print("Estudio en el Simon bolivar")
print("No tengo ni la minima idea de que estudiar")
print("Estoy en area 1 por me gustan las mates")
print("No se que puedo crar con python")
print("A la universidad que quiero entrar es CU")
print("No me gutsa la programacion en lo absoluto :o")
print("Mi comic favorito es el de spider-man")
print("Mi comida favorita son las enchiladas suizas")
print("Pienso que las matematicas son divertidas")
print("Me gusta andar en bicicleta")
print("No me eh roto ningun hueso")
print("Tengo una novia preciosa")
print("Tengo una perrita llamada flor")
print("Me gusta jugar fornite y roblox")
print("Me gusta jugar lol")
print("Me gusta salir a camina de vez en cuado")
print("Un país que me gustaria visitar es suiza")
print("No tengo trabajo")
print("Odio a mi compañero Rodrigo")